<?xml version="1.0" encoding="UTF-8"?>
<?altova_samplexml Govaerts_Sample.xml?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<Distributions>
			<xsl:for-each select="//Distribution">
				<xsl:variable name="vRegion">
					<xsl:call-template name="conRegion">
						<xsl:with-param name="pRegion" select="Region"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:if test="$vRegion!=''">
					<Distribution>
						<xsl:attribute name="schema">TDWG Level <xsl:value-of select="substring-after(Schema,'TDWG')"/></xsl:attribute>
						
						<xsl:attribute name="region"><xsl:value-of select="$vRegion"/></xsl:attribute>
						<xsl:attribute name="occurrence"><xsl:value-of select="Occurrence"/></xsl:attribute>
						<xsl:attribute name="origin"><xsl:value-of select="Origin"/></xsl:attribute>
					</Distribution>
				</xsl:if>
			</xsl:for-each>
		</Distributions>
	</xsl:template>
	<xsl:template name="conRegion">
		<xsl:param name="pRegion"/>
		<xsl:choose>
			<xsl:when test="$pRegion='1'">1</xsl:when>
			<xsl:when test="$pRegion='12'">12</xsl:when>
			<xsl:when test="$pRegion='2'">2</xsl:when>
			<xsl:when test="$pRegion='26'">26</xsl:when>
			<xsl:when test="$pRegion='27'">27</xsl:when>
			<xsl:when test="$pRegion='29'">29</xsl:when>
			<xsl:when test="$pRegion='3'">3</xsl:when>
			<xsl:when test="$pRegion='33'">33</xsl:when>
			<xsl:when test="$pRegion='34'">34</xsl:when>
			<xsl:when test="$pRegion='35'">35</xsl:when>
			<xsl:when test="$pRegion='36'">36</xsl:when>
			<xsl:when test="$pRegion='40'">40</xsl:when>
			<xsl:when test="$pRegion='42'">42</xsl:when>
			<xsl:when test="$pRegion='51'">51</xsl:when>
			<xsl:when test="$pRegion='71'">71</xsl:when>
			<xsl:when test="$pRegion='73'">73</xsl:when>
			<xsl:when test="$pRegion='78'">78</xsl:when>
			<xsl:when test="$pRegion='79'">79</xsl:when>
			<xsl:when test="$pRegion='81'">81</xsl:when>
			<xsl:when test="$pRegion='84'">84</xsl:when>
			<xsl:when test="$pRegion='AG'">AG</xsl:when>
			<xsl:when test="$pRegion='AG+'">AG+</xsl:when>
			<xsl:when test="$pRegion='AGE'">AGE</xsl:when>
			<xsl:when test="$pRegion='AGS'">AGS</xsl:when>
			<xsl:when test="$pRegion='ALB'">ALB</xsl:when>
			<xsl:when test="$pRegion='ARI'">ARI</xsl:when>
			<xsl:when test="$pRegion='AUT'">AUT</xsl:when>
			<xsl:when test="$pRegion='BAH'">BAH</xsl:when>
			<xsl:when test="$pRegion='BGM'">BGM</xsl:when>
			<xsl:when test="$pRegion='BRC'">BRC</xsl:when>
			<xsl:when test="$pRegion='BUR'">BUR</xsl:when>
			<xsl:when test="$pRegion='BZL'">BZL</xsl:when>
			<xsl:when test="$pRegion='CAL'">CAL</xsl:when>
			<xsl:when test="$pRegion='CHM'">CHM</xsl:when>
			<xsl:when test="$pRegion='CL+'">CL+</xsl:when>
			<xsl:when test="$pRegion='CLM'">CLM</xsl:when>
			<xsl:when test="$pRegion='CLS'">CLS</xsl:when>
			<xsl:when test="$pRegion='CMN'">CMN</xsl:when>
			<xsl:when test="$pRegion='COR'">COR</xsl:when>
			<xsl:when test="$pRegion='CUB'">CUB</xsl:when>
			<xsl:when test="$pRegion='CZE'">CZE</xsl:when>
			<xsl:when test="$pRegion='EAI'">EAI</xsl:when>
			<xsl:when test="$pRegion='ECU'">ECU</xsl:when>
			<xsl:when test="$pRegion='EGY'">EGY</xsl:when>
			<xsl:when test="$pRegion='ETH'">ETH</xsl:when>
			<xsl:when test="$pRegion='FAL'">FAL</xsl:when>
			<xsl:when test="$pRegion='FLA'">FLA</xsl:when>
			<xsl:when test="$pRegion='FRA'">FRA</xsl:when>
			<xsl:when test="$pRegion='GNL'">GNL</xsl:when>
			<xsl:when test="$pRegion='GUA'">GUA</xsl:when>
			<xsl:when test="$pRegion='GUY'">GUY</xsl:when>
			<xsl:when test="$pRegion='ILL'">ILL</xsl:when>
			<xsl:when test="$pRegion='IRN'">IRN</xsl:when>
			<xsl:when test="$pRegion='ITA'">ITA</xsl:when>
			<xsl:when test="$pRegion='JAP'">JAP</xsl:when>
			<xsl:when test="$pRegion='JMK'">JMK</xsl:when>
			<xsl:when test="$pRegion='KAZ'">KAZ</xsl:when>
			<xsl:when test="$pRegion='KRI'">KRI</xsl:when>
			<xsl:when test="$pRegion='LBY'">LBY</xsl:when>
			<xsl:when test="$pRegion='MAU'">MAU</xsl:when>
			<xsl:when test="$pRegion='MIC'">MIC</xsl:when>
			<xsl:when test="$pRegion='MIN'">MIN</xsl:when>
			<xsl:when test="$pRegion='MOL'">MOL</xsl:when>
			<xsl:when test="$pRegion='MOR'">MOR</xsl:when>
			<xsl:when test="$pRegion='MSO'">MSO</xsl:when>
			<xsl:when test="$pRegion='MXC'">MXC</xsl:when>
			<xsl:when test="$pRegion='MXE'">MXE</xsl:when>
			<xsl:when test="$pRegion='MYA'">MYA</xsl:when>
			<xsl:when test="$pRegion='NCS'">NCS</xsl:when>
			<xsl:when test="$pRegion='NEB'">NEB</xsl:when>
			<xsl:when test="$pRegion='NSW'">NSW</xsl:when>
			<xsl:when test="$pRegion='NWG'">NWG</xsl:when>
			<xsl:when test="$pRegion='NWM'">NWM</xsl:when>
			<xsl:when test="$pRegion='NWY'">NWY</xsl:when>
			<xsl:when test="$pRegion='NZN'">NZN</xsl:when>
			<xsl:when test="$pRegion='NZS'">NZS</xsl:when>
			<xsl:when test="$pRegion='ORE'">ORE</xsl:when>
			<xsl:when test="$pRegion='PAL'">PAL</xsl:when>
			<xsl:when test="$pRegion='PAN'">PAN</xsl:when>
			<xsl:when test="$pRegion='PAR'">PAR</xsl:when>
			<xsl:when test="$pRegion='PHI'">PHI</xsl:when>
			<xsl:when test="$pRegion='ROM'">ROM</xsl:when>
			<xsl:when test="$pRegion='SAR'">SAR</xsl:when>
			<xsl:when test="$pRegion='SAS'">SAS</xsl:when>
			<xsl:when test="$pRegion='SUR'">SUR</xsl:when>
			<xsl:when test="$pRegion='SVA'">SVA</xsl:when>
			<xsl:when test="$pRegion='THA'">THA</xsl:when>
			<xsl:when test="$pRegion='TZK'">TZK</xsl:when>
			<xsl:when test="$pRegion='UGA'">UGA</xsl:when>
			<xsl:when test="$pRegion='UKR'">UKR</xsl:when>
			<xsl:when test="$pRegion='URU'">URU</xsl:when>
			<xsl:when test="$pRegion='VAN'">VAN</xsl:when>
			<xsl:when test="$pRegion='VEN'">VEN</xsl:when>
			<xsl:when test="$pRegion='VIE'">VIE</xsl:when>
			<xsl:when test="$pRegion='WAS'">WAS</xsl:when>
			<xsl:when test="$pRegion='WAU'">WAU</xsl:when>
			<xsl:when test="$pRegion='WSB'">WSB</xsl:when>
			<xsl:when test="$pRegion='WYO'">WYO</xsl:when>
			<xsl:when test="$pRegion='ZAI'">ZAI</xsl:when>
			<xsl:when test="$pRegion='ZIM'">ZIM</xsl:when>
			<xsl:when test="$pRegion='11'">11</xsl:when>
			<xsl:when test="$pRegion='13'">13</xsl:when>
			<xsl:when test="$pRegion='14'">14</xsl:when>
			<xsl:when test="$pRegion='20'">20</xsl:when>
			<xsl:when test="$pRegion='22'">22</xsl:when>
			<xsl:when test="$pRegion='30'">30</xsl:when>
			<xsl:when test="$pRegion='32'">32</xsl:when>
			<xsl:when test="$pRegion='50'">50</xsl:when>
			<xsl:when test="$pRegion='7'">7</xsl:when>
			<xsl:when test="$pRegion='72'">72</xsl:when>
			<xsl:when test="$pRegion='8'">8</xsl:when>
			<xsl:when test="$pRegion='80'">80</xsl:when>
			<xsl:when test="$pRegion='85'">85</xsl:when>
			<xsl:when test="$pRegion='AFG'">AFG</xsl:when>
			<xsl:when test="$pRegion='AGW'">AGW</xsl:when>
			<xsl:when test="$pRegion='ALG'">ALG</xsl:when>
			<xsl:when test="$pRegion='ALT'">ALT</xsl:when>
			<xsl:when test="$pRegion='ANG'">ANG</xsl:when>
			<xsl:when test="$pRegion='ASK'">ASK</xsl:when>
			<xsl:when test="$pRegion='ASS'">ASS</xsl:when>
			<xsl:when test="$pRegion='BAL'">BAL</xsl:when>
			<xsl:when test="$pRegion='BOL'">BOL</xsl:when>
			<xsl:when test="$pRegion='BUL'">BUL</xsl:when>
			<xsl:when test="$pRegion='BZC'">BZC</xsl:when>
			<xsl:when test="$pRegion='BZS'">BZS</xsl:when>
			<xsl:when test="$pRegion='CHC'">CHC</xsl:when>
			<xsl:when test="$pRegion='CHS'">CHS</xsl:when>
			<xsl:when test="$pRegion='CHT'">CHT</xsl:when>
			<xsl:when test="$pRegion='CLC'">CLC</xsl:when>
			<xsl:when test="$pRegion='CLN'">CLN</xsl:when>
			<xsl:when test="$pRegion='CNY'">CNY</xsl:when>
			<xsl:when test="$pRegion='COL'">COL</xsl:when>
			<xsl:when test="$pRegion='COS'">COS</xsl:when>
			<xsl:when test="$pRegion='CPP'">CPP</xsl:when>
			<xsl:when test="$pRegion='CVI'">CVI</xsl:when>
			<xsl:when test="$pRegion='CYP'">CYP</xsl:when>
			<xsl:when test="$pRegion='DOM'">DOM</xsl:when>
			<xsl:when test="$pRegion='EHM'">EHM</xsl:when>
			<xsl:when test="$pRegion='FRG'">FRG</xsl:when>
			<xsl:when test="$pRegion='GER'">GER</xsl:when>
			<xsl:when test="$pRegion='GGI'">GGI</xsl:when>
			<xsl:when test="$pRegion='GRB'">GRB</xsl:when>
			<xsl:when test="$pRegion='GRC'">GRC</xsl:when>
			<xsl:when test="$pRegion='HAI'">HAI</xsl:when>
			<xsl:when test="$pRegion='HAW'">HAW</xsl:when>
			<xsl:when test="$pRegion='HUN'">HUN</xsl:when>
			<xsl:when test="$pRegion='IDA'">IDA</xsl:when>
			<xsl:when test="$pRegion='IND'">IND</xsl:when>
			<xsl:when test="$pRegion='IOW'">IOW</xsl:when>
			<xsl:when test="$pRegion='IRQ'">IRQ</xsl:when>
			<xsl:when test="$pRegion='JAM'">JAM</xsl:when>
			<xsl:when test="$pRegion='JAW'">JAW</xsl:when>
			<xsl:when test="$pRegion='KAM'">KAM</xsl:when>
			<xsl:when test="$pRegion='KEN'">KEN</xsl:when>
			<xsl:when test="$pRegion='KOR'">KOR</xsl:when>
			<xsl:when test="$pRegion='KRY'">KRY</xsl:when>
			<xsl:when test="$pRegion='KTY'">KTY</xsl:when>
			<xsl:when test="$pRegion='LBS'">LBS</xsl:when>
			<xsl:when test="$pRegion='LEE'">LEE</xsl:when>
			<xsl:when test="$pRegion='MAI'">MAI</xsl:when>
			<xsl:when test="$pRegion='MDG'">MDG</xsl:when>
			<xsl:when test="$pRegion='MDR'">MDR</xsl:when>
			<xsl:when test="$pRegion='MLY'">MLY</xsl:when>
			<xsl:when test="$pRegion='MNT'">MNT</xsl:when>
			<xsl:when test="$pRegion='MON'">MON</xsl:when>
			<xsl:when test="$pRegion='MOZ'">MOZ</xsl:when>
			<xsl:when test="$pRegion='MRY'">MRY</xsl:when>
			<xsl:when test="$pRegion='MXN'">MXN</xsl:when>
			<xsl:when test="$pRegion='MXS'">MXS</xsl:when>
			<xsl:when test="$pRegion='NAT'">NAT</xsl:when>
			<xsl:when test="$pRegion='NCA'">NCA</xsl:when>
			<xsl:when test="$pRegion='NDA'">NDA</xsl:when>
			<xsl:when test="$pRegion='NEP'">NEP</xsl:when>
			<xsl:when test="$pRegion='NEV'">NEV</xsl:when>
			<xsl:when test="$pRegion='NOR'">NOR</xsl:when>
			<xsl:when test="$pRegion='PER'">PER</xsl:when>
			<xsl:when test="$pRegion='POL'">POL</xsl:when>
			<xsl:when test="$pRegion='POR'">POR</xsl:when>
			<xsl:when test="$pRegion='PRM'">PRM</xsl:when>
			<xsl:when test="$pRegion='QUE'">QUE</xsl:when>
			<xsl:when test="$pRegion='REU'">REU</xsl:when>
			<xsl:when test="$pRegion='RUS'">RUS</xsl:when>
			<xsl:when test="$pRegion='SAK'">SAK</xsl:when>
			<xsl:when test="$pRegion='SDA'">SDA</xsl:when>
			<xsl:when test="$pRegion='SIC'">SIC</xsl:when>
			<xsl:when test="$pRegion='SPA'">SPA</xsl:when>
			<xsl:when test="$pRegion='SWI'">SWI</xsl:when>
			<xsl:when test="$pRegion='TAI'">TAI</xsl:when>
			<xsl:when test="$pRegion='TCS'">TCS</xsl:when>
			<xsl:when test="$pRegion='TEX'">TEX</xsl:when>
			<xsl:when test="$pRegion='TUN'">TUN</xsl:when>
			<xsl:when test="$pRegion='TUR'">TUR</xsl:when>
			<xsl:when test="$pRegion='TVL'">TVL</xsl:when>
			<xsl:when test="$pRegion='UTA'">UTA</xsl:when>
			<xsl:when test="$pRegion='VRG'">VRG</xsl:when>
			<xsl:when test="$pRegion='WHM'">WHM</xsl:when>
			<xsl:when test="$pRegion='YAK'">YAK</xsl:when>
			<xsl:when test="$pRegion='YEM'">YEM</xsl:when>
			<xsl:when test="$pRegion='YUG'">YUG</xsl:when>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>
